// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class EDObject {

	public string strName = "none";
	public float fMinPos;
	public float fMaxPos;
	public float fRangPosY;
	public float fOffsetPosY;
	public float fMinScale;
	public float fMaxScale;
	
	public EDObject(string name)
	{
		strName = name;
	}
	
	public void setData (float minPos, float maxPos, float rangePosY, float offsetPosY, float minScale, float maxScale)
	{
		fMinPos = minPos;
		fMaxPos = maxPos;
		fRangPosY = rangePosY;
		fOffsetPosY = offsetPosY;
		fMinScale = minScale;
		fMaxScale = maxScale;
	}
	
}
